# Slim container for running SQL*Plus (ARM compatible)
FROM oraclelinux:8-slim
ARG release=19
ARG update=10
RUN  microdnf -y install oracle-release-el8 && \
     microdnf -y install oracle-instantclient${release}.${update}-sqlplus && \
     rm -rf /var/cache/yum
ENTRYPOINT ["/usr/bin/sqlplus"]